DEVELOPMENT_PORT = 9008
TESTING_PORT = 9008
PRODUCTION_PORT = 9008


LOCAL_DB_NAME="giani"
LOCAL_USER="yichun"
LOCAL_HOST="localhost"
LOCAL_PASSWORD="chachun88"


ONDEV_DB_NAME="test_giani"
ONDEV_USER="yichun"
ONDEV_HOST="localhost"
ONDEV_PASSWORD="chachun88"


ONTEST_DB_NAME="test_giani"
ONTEST_USER="yichun"
ONTEST_HOST="localhost"
ONTEST_PASSWORD="chachun88"


PRODUCTION_DB_NAME="test_giani"
PRODUCTION_USER="yichun"
PRODUCTION_HOST="localhost"
PRODUCTION_PASSWORD="chachun88"
